// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjc1_paB1H0MZ59rafmqugkAfAq49QEf0',
    appId: '1:444220004342:web:8ca6f05f5a79871e7719d7',
    messagingSenderId: '444220004342',
    projectId: 'finance-researchproject',
    authDomain: 'finance-researchproject.firebaseapp.com',
    storageBucket: 'finance-researchproject.firebasestorage.app',
    measurementId: 'G-VL8VJEEJHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDjNQDGJw2vp99PxEUXZQqUVekT38XfY',
    appId: '1:444220004342:android:7ef910a87ea5351a7719d7',
    messagingSenderId: '444220004342',
    projectId: 'finance-researchproject',
    storageBucket: 'finance-researchproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Y0cyy9lPnfdeo_Md7I3TT9WAyksCNiI',
    appId: '1:444220004342:ios:30c01443cd6f0c187719d7',
    messagingSenderId: '444220004342',
    projectId: 'finance-researchproject',
    storageBucket: 'finance-researchproject.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjc1_paB1H0MZ59rafmqugkAfAq49QEf0',
    appId: '1:444220004342:web:8ca6f05f5a79871e7719d7',
    messagingSenderId: '444220004342',
    projectId: 'finance-researchproject',
    authDomain: 'finance-researchproject.firebaseapp.com',
    storageBucket: 'finance-researchproject.firebasestorage.app',
    measurementId: 'G-VL8VJEEJHL',
  );

}